import 'surah.dart';

List<Surah> surahsData = [
  Surah(
      number: 1,
      name: 'الفاتحة',
      enName: 'Al-Faatiha',
      enNameTrans: 'The Opening',
      numberOfAyahs: 7,
      place: 'Meccan'),
  Surah(
      number: 2,
      name: 'البقرة',
      enName: 'Al-Baqara',
      enNameTrans: 'The Cow',
      numberOfAyahs: 286,
      place: 'Medinan'),
  Surah(
      number: 3,
      name: 'ال عمران',
      enName: 'Aal-i-Imraan',
      enNameTrans: 'The Family of Imraan',
      numberOfAyahs: 200,
      place: 'Medinan'),
  Surah(
      number: 4,
      name: 'النساء',
      enName: 'An-Nisaa',
      enNameTrans: 'The Women',
      numberOfAyahs: 176,
      place: 'Medinan'),
  Surah(
      number: 5,
      name: 'المائدة',
      enName: 'Al-Maaida',
      enNameTrans: 'The Table',
      numberOfAyahs: 120,
      place: 'Medinan'),
  Surah(
      number: 6,
      name: 'الأنعام',
      enName: "Al-An'aam",
      enNameTrans: 'The Cattle',
      numberOfAyahs: 165,
      place: 'Meccan'),
  Surah(
      number: 7,
      name: 'الأعراف',
      enName: "Al-A'raaf",
      enNameTrans: 'The Heights',
      numberOfAyahs: 206,
      place: 'Meccan'),
  Surah(
      number: 8,
      name: 'الأنفال',
      enName: 'Al-Anfaal',
      enNameTrans: 'The Spoils of War',
      numberOfAyahs: 75,
      place: 'Medinan'),
  Surah(
      number: 9,
      name: 'التوبة',
      enName: 'At-Tawba',
      enNameTrans: 'The Repentance',
      numberOfAyahs: 129,
      place: 'Medinan'),
  Surah(
      number: 10,
      name: 'يونس',
      enName: 'Yunus',
      enNameTrans: 'Jonas',
      numberOfAyahs: 109,
      place: 'Meccan'),
  Surah(
      number: 11,
      name: 'هود',
      enName: 'Hud',
      enNameTrans: 'Hud',
      numberOfAyahs: 123,
      place: 'Meccan'),
  Surah(
      number: 12,
      name: 'يوسف',
      enName: 'Yusuf',
      enNameTrans: 'Joseph',
      numberOfAyahs: 111,
      place: 'Meccan'),
  Surah(
      number: 13,
      name: 'الرعد',
      enName: "Ar-Ra'd",
      enNameTrans: 'The Thunder',
      numberOfAyahs: 43,
      place: 'Medinan'),
  Surah(
      number: 14,
      name: 'إبراهيم',
      enName: 'Ibrahim',
      enNameTrans: 'Abraham',
      numberOfAyahs: 52,
      place: 'Meccan'),
  Surah(
      number: 15,
      name: 'الحجر',
      enName: 'Al-Hijr',
      enNameTrans: 'The Rock',
      numberOfAyahs: 99,
      place: 'Meccan'),
  Surah(
      number: 16,
      name: 'النحل',
      enName: 'An-Nahl',
      enNameTrans: 'The Bee',
      numberOfAyahs: 128,
      place: 'Meccan'),
  Surah(
      number: 17,
      name: 'الإسراء',
      enName: 'Al-Israa',
      enNameTrans: 'The Night Journey',
      numberOfAyahs: 111,
      place: 'Meccan'),
  Surah(
      number: 18,
      name: 'الكهف',
      enName: 'Al-Kahf',
      enNameTrans: 'The Cave',
      numberOfAyahs: 110,
      place: 'Meccan'),
  Surah(
      number: 19,
      name: 'مريم',
      enName: 'Maryam',
      enNameTrans: 'Mary',
      numberOfAyahs: 98,
      place: 'Meccan'),
  Surah(
      number: 20,
      name: 'طه',
      enName: 'Taa-Haa',
      enNameTrans: 'Taa-Haa',
      numberOfAyahs: 135,
      place: 'Meccan'),
  Surah(
      number: 21,
      name: 'الأنبياء',
      enName: 'Al-Anbiyaa',
      enNameTrans: 'The Prophets',
      numberOfAyahs: 112,
      place: 'Meccan'),
  Surah(
      number: 22,
      name: 'الحج',
      enName: 'Al-Hajj',
      enNameTrans: 'The Pilgrimage',
      numberOfAyahs: 78,
      place: 'Medinan'),
  Surah(
      number: 23,
      name: 'المؤمنون',
      enName: 'Al-Muminoon',
      enNameTrans: 'The Believers',
      numberOfAyahs: 118,
      place: 'Meccan'),
  Surah(
      number: 24,
      name: 'النور',
      enName: 'An-Noor',
      enNameTrans: 'The Light',
      numberOfAyahs: 64,
      place: 'Medinan'),
  Surah(
      number: 25,
      name: 'الفرقان',
      enName: 'Al-Furqaan',
      enNameTrans: 'The Criterion',
      numberOfAyahs: 77,
      place: 'Meccan'),
  Surah(
      number: 26,
      name: 'الشعراء',
      enName: "Ash-Shu'araa",
      enNameTrans: 'The Poets',
      numberOfAyahs: 227,
      place: 'Meccan'),
  Surah(
      number: 27,
      name: 'النمل',
      enName: 'An-Naml',
      enNameTrans: 'The Ant',
      numberOfAyahs: 93,
      place: 'Meccan'),
  Surah(
      number: 28,
      name: 'القصص',
      enName: 'Al-Qasas',
      enNameTrans: 'The Stories',
      numberOfAyahs: 88,
      place: 'Meccan'),
  Surah(
      number: 29,
      name: 'العنكبوت',
      enName: 'Al-Ankaboot',
      enNameTrans: 'The Spider',
      numberOfAyahs: 69,
      place: 'Meccan'),
  Surah(
      number: 30,
      name: 'الروم',
      enName: 'Ar-Room',
      enNameTrans: 'The Romans',
      numberOfAyahs: 60,
      place: 'Meccan'),
  Surah(
      number: 31,
      name: 'لقمان',
      enName: 'Luqman',
      enNameTrans: 'Luqman',
      numberOfAyahs: 34,
      place: 'Meccan'),
  Surah(
      number: 32,
      name: 'السجدة',
      enName: 'As-Sajda',
      enNameTrans: 'The Prostration',
      numberOfAyahs: 30,
      place: 'Meccan'),
  Surah(
      number: 33,
      name: 'الأحزاب',
      enName: 'Al-Ahzaab',
      enNameTrans: 'The Clans',
      numberOfAyahs: 73,
      place: 'Medinan'),
  Surah(
      number: 34,
      name: 'سبإ',
      enName: 'Saba',
      enNameTrans: 'Sheba',
      numberOfAyahs: 54,
      place: 'Meccan'),
  Surah(
      number: 35,
      name: 'فاطر',
      enName: 'Faatir',
      enNameTrans: 'The Originator',
      numberOfAyahs: 45,
      place: 'Meccan'),
  Surah(
      number: 36,
      name: 'يس',
      enName: 'Yaseen',
      enNameTrans: 'Yaseen',
      numberOfAyahs: 83,
      place: 'Meccan'),
  Surah(
      number: 37,
      name: 'الصافات',
      enName: 'As-Saaffaat',
      enNameTrans: 'Those drawn up in Ranks',
      numberOfAyahs: 182,
      place: 'Meccan'),
  Surah(
      number: 38,
      name: 'ص',
      enName: 'Saad',
      enNameTrans: 'The letter Saad',
      numberOfAyahs: 88,
      place: 'Meccan'),
  Surah(
      number: 39,
      name: 'الزمر',
      enName: 'Az-Zumar',
      enNameTrans: 'The Groups',
      numberOfAyahs: 75,
      place: 'Meccan'),
  Surah(
      number: 40,
      name: 'غافر',
      enName: 'Ghafir',
      enNameTrans: 'The Forgiver',
      numberOfAyahs: 85,
      place: 'Meccan'),
  Surah(
      number: 41,
      name: 'فصلت',
      enName: 'Fussilat',
      enNameTrans: 'Explained in detail',
      numberOfAyahs: 54,
      place: 'Meccan'),
  Surah(
      number: 42,
      name: 'الشورى',
      enName: 'Ash-Shura',
      enNameTrans: 'Consultation',
      numberOfAyahs: 53,
      place: 'Meccan'),
  Surah(
      number: 43,
      name: 'الزخرف',
      enName: 'Az-Zukhruf',
      enNameTrans: 'Ornaments of gold',
      numberOfAyahs: 89,
      place: 'Meccan'),
  Surah(
      number: 44,
      name: 'الدخان',
      enName: 'Ad-Dukhaan',
      enNameTrans: 'The Smoke',
      numberOfAyahs: 59,
      place: 'Meccan'),
  Surah(
      number: 45,
      name: 'الجاثية',
      enName: 'Al-Jaathiya',
      enNameTrans: 'Crouching',
      numberOfAyahs: 37,
      place: 'Meccan'),
  Surah(
      number: 46,
      name: 'الأحقاف',
      enName: 'Al-Ahqaf',
      enNameTrans: 'The Dunes',
      numberOfAyahs: 35,
      place: 'Meccan'),
  Surah(
      number: 47,
      name: 'محمد',
      enName: 'Muhammad',
      enNameTrans: 'Muhammad',
      numberOfAyahs: 38,
      place: 'Medinan'),
  Surah(
      number: 48,
      name: 'الفتح',
      enName: 'Al-Fath',
      enNameTrans: 'The Victory',
      numberOfAyahs: 29,
      place: 'Medinan'),
  Surah(
      number: 49,
      name: 'الحجرات',
      enName: 'Al-Hujuraat',
      enNameTrans: 'The Inner Apartments',
      numberOfAyahs: 18,
      place: 'Medinan'),
  Surah(
      number: 50,
      name: 'ق',
      enName: 'Qaaf',
      enNameTrans: 'The letter Qaaf',
      numberOfAyahs: 45,
      place: 'Meccan'),
  Surah(
      number: 51,
      name: 'الذاريات',
      enName: 'Adh-Dhaariyat',
      enNameTrans: 'The Winnowing Winds',
      numberOfAyahs: 60,
      place: 'Meccan'),
  Surah(
      number: 52,
      name: 'الطور',
      enName: 'At-Tur',
      enNameTrans: 'The Mount',
      numberOfAyahs: 49,
      place: 'Meccan'),
  Surah(
      number: 53,
      name: 'النجم',
      enName: 'An-Najm',
      enNameTrans: 'The Star',
      numberOfAyahs: 62,
      place: 'Meccan'),
  Surah(
      number: 54,
      name: 'القمر',
      enName: 'Al-Qamar',
      enNameTrans: 'The Moon',
      numberOfAyahs: 55,
      place: 'Meccan'),
  Surah(
      number: 55,
      name: 'الرحمن',
      enName: 'Ar-Rahmaan',
      enNameTrans: 'The Beneficent',
      numberOfAyahs: 78,
      place: 'Medinan'),
  Surah(
      number: 56,
      name: 'الواقعة',
      enName: 'Al-Waaqia',
      enNameTrans: 'The Inevitable',
      numberOfAyahs: 96,
      place: 'Meccan'),
  Surah(
      number: 57,
      name: 'الحديد',
      enName: 'Al-Hadid',
      enNameTrans: 'The Iron',
      numberOfAyahs: 29,
      place: 'Medinan'),
  Surah(
      number: 58,
      name: 'المجادلة',
      enName: 'Al-Mujaadila',
      enNameTrans: 'The Pleading Woman',
      numberOfAyahs: 22,
      place: 'Medinan'),
  Surah(
      number: 59,
      name: 'الحشر',
      enName: 'Al-Hashr',
      enNameTrans: 'The Exile',
      numberOfAyahs: 24,
      place: 'Medinan'),
  Surah(
      number: 60,
      name: 'الممتحنة',
      enName: 'Al-Mumtahana',
      enNameTrans: 'She that is to be examined',
      numberOfAyahs: 13,
      place: 'Medinan'),
  Surah(
      number: 61,
      name: 'الصف',
      enName: 'As-Saff',
      enNameTrans: 'The Ranks',
      numberOfAyahs: 14,
      place: 'Medinan'),
  Surah(
      number: 62,
      name: 'الجمعة',
      enName: "Al-Jumu'a",
      enNameTrans: 'Friday',
      numberOfAyahs: 11,
      place: 'Medinan'),
  Surah(
      number: 63,
      name: 'المنافقون',
      enName: 'Al-Munaafiqoon',
      enNameTrans: 'The Hypocrites',
      numberOfAyahs: 11,
      place: 'Medinan'),
  Surah(
      number: 64,
      name: 'التغابن',
      enName: 'At-Taghaabun',
      enNameTrans: 'Mutual Disillusion',
      numberOfAyahs: 18,
      place: 'Medinan'),
  Surah(
      number: 65,
      name: 'الطلاق',
      enName: 'At-Talaaq',
      enNameTrans: 'Divorce',
      numberOfAyahs: 12,
      place: 'Medinan'),
  Surah(
      number: 66,
      name: 'التحريم',
      enName: 'At-Tahrim',
      enNameTrans: 'The Prohibition',
      numberOfAyahs: 12,
      place: 'Medinan'),
  Surah(
      number: 67,
      name: 'الملك',
      enName: 'Al-Mulk',
      enNameTrans: 'The Sovereignty',
      numberOfAyahs: 30,
      place: 'Meccan'),
  Surah(
      number: 68,
      name: 'القلم',
      enName: 'Al-Qalam',
      enNameTrans: 'The Pen',
      numberOfAyahs: 52,
      place: 'Meccan'),
  Surah(
      number: 69,
      name: 'الحاقة',
      enName: 'Al-Haaqqa',
      enNameTrans: 'The Reality',
      numberOfAyahs: 52,
      place: 'Meccan'),
  Surah(
      number: 70,
      name: 'المعارج',
      enName: "Al-Ma'aarij",
      enNameTrans: 'The Ascending Stairways',
      numberOfAyahs: 44,
      place: 'Meccan'),
  Surah(
      number: 71,
      name: 'نوح',
      enName: 'Nooh',
      enNameTrans: 'Noah',
      numberOfAyahs: 28,
      place: 'Meccan'),
  Surah(
      number: 72,
      name: 'الجن',
      enName: 'Al-Jinn',
      enNameTrans: 'The Jinn',
      numberOfAyahs: 28,
      place: 'Meccan'),
  Surah(
      number: 73,
      name: 'المزمل',
      enName: 'Al-Muzzammil',
      enNameTrans: 'The Enshrouded One',
      numberOfAyahs: 20,
      place: 'Meccan'),
  Surah(
      number: 74,
      name: 'المدثر',
      enName: 'Al-Muddaththir',
      enNameTrans: 'The Cloaked One',
      numberOfAyahs: 56,
      place: 'Meccan'),
  Surah(
      number: 75,
      name: 'القيامة',
      enName: 'Al-Qiyaama',
      enNameTrans: 'The Resurrection',
      numberOfAyahs: 40,
      place: 'Meccan'),
  Surah(
      number: 76,
      name: 'الإنسان',
      enName: 'Al-Insaan',
      enNameTrans: 'Man',
      numberOfAyahs: 31,
      place: 'Medinan'),
  Surah(
      number: 77,
      name: 'المرسلات',
      enName: 'Al-Mursalaat',
      enNameTrans: 'The Emissaries',
      numberOfAyahs: 50,
      place: 'Meccan'),
  Surah(
      number: 78,
      name: 'النبإ',
      enName: 'An-Naba',
      enNameTrans: 'The Announcement',
      numberOfAyahs: 40,
      place: 'Meccan'),
  Surah(
      number: 79,
      name: 'النازعات',
      enName: "An-Naazi'aat",
      enNameTrans: 'Those who drag forth',
      numberOfAyahs: 46,
      place: 'Meccan'),
  Surah(
      number: 80,
      name: 'عبس',
      enName: 'Abasa',
      enNameTrans: 'He frowned',
      numberOfAyahs: 42,
      place: 'Meccan'),
  Surah(
      number: 81,
      name: 'التكوير',
      enName: 'At-Takwir',
      enNameTrans: 'The Overthrowing',
      numberOfAyahs: 29,
      place: 'Meccan'),
  Surah(
      number: 82,
      name: 'الانفطار',
      enName: 'Al-Infitaar',
      enNameTrans: 'The Cleaving',
      numberOfAyahs: 19,
      place: 'Meccan'),
  Surah(
      number: 83,
      name: 'المطففين',
      enName: 'Al-Mutaffifin',
      enNameTrans: 'Defrauding',
      numberOfAyahs: 36,
      place: 'Meccan'),
  Surah(
      number: 84,
      name: 'الانشقاق',
      enName: 'Al-Inshiqaaq',
      enNameTrans: 'The Splitting Open',
      numberOfAyahs: 25,
      place: 'Meccan'),
  Surah(
      number: 85,
      name: 'البروج',
      enName: 'Al-Burooj',
      enNameTrans: 'The Constellations',
      numberOfAyahs: 22,
      place: 'Meccan'),
  Surah(
      number: 86,
      name: 'الطارق',
      enName: 'At-Taariq',
      enNameTrans: 'The Morning Star',
      numberOfAyahs: 17,
      place: 'Meccan'),
  Surah(
      number: 87,
      name: 'الأعلى',
      enName: "Al-A'laa",
      enNameTrans: 'The Most High',
      numberOfAyahs: 19,
      place: 'Meccan'),
  Surah(
      number: 88,
      name: 'الغاشية',
      enName: 'Al-Ghaashiya',
      enNameTrans: 'The Overwhelming',
      numberOfAyahs: 26,
      place: 'Meccan'),
  Surah(
      number: 89,
      name: 'الفجر',
      enName: 'Al-Fajr',
      enNameTrans: 'The Dawn',
      numberOfAyahs: 30,
      place: 'Meccan'),
  Surah(
      number: 90,
      name: 'البلد',
      enName: 'Al-Balad',
      enNameTrans: 'The City',
      numberOfAyahs: 20,
      place: 'Meccan'),
  Surah(
      number: 91,
      name: 'الشمس',
      enName: 'Ash-Shams',
      enNameTrans: 'The Sun',
      numberOfAyahs: 15,
      place: 'Meccan'),
  Surah(
      number: 92,
      name: 'الليل',
      enName: 'Al-Lail',
      enNameTrans: 'The Night',
      numberOfAyahs: 21,
      place: 'Meccan'),
  Surah(
      number: 93,
      name: 'الضحى',
      enName: 'Ad-Dhuhaa',
      enNameTrans: 'The Morning Hours',
      numberOfAyahs: 11,
      place: 'Meccan'),
  Surah(
      number: 94,
      name: 'الشرح',
      enName: 'Ash-Sharh',
      enNameTrans: 'The Consolation',
      numberOfAyahs: 8,
      place: 'Meccan'),
  Surah(
      number: 95,
      name: 'التين',
      enName: 'At-Tin',
      enNameTrans: 'The Fig',
      numberOfAyahs: 8,
      place: 'Meccan'),
  Surah(
      number: 96,
      name: 'العلق',
      enName: 'Al-Alaq',
      enNameTrans: 'The Clot',
      numberOfAyahs: 19,
      place: 'Meccan'),
  Surah(
      number: 97,
      name: 'القدر',
      enName: 'Al-Qadr',
      enNameTrans: 'The Power, Fate',
      numberOfAyahs: 5,
      place: 'Meccan'),
  Surah(
      number: 98,
      name: 'البينة',
      enName: 'Al-Bayyina',
      enNameTrans: 'The Evidence',
      numberOfAyahs: 8,
      place: 'Medinan'),
  Surah(
      number: 99,
      name: 'الزلزلة',
      enName: 'Az-Zalzala',
      enNameTrans: 'The Earthquake',
      numberOfAyahs: 8,
      place: 'Medinan'),
  Surah(
      number: 100,
      name: 'العاديات',
      enName: 'Al-Aadiyaat',
      enNameTrans: 'The Chargers',
      numberOfAyahs: 11,
      place: 'Meccan'),
  Surah(
      number: 101,
      name: 'القارعة',
      enName: "Al-Qaari'a",
      enNameTrans: 'The Calamity',
      numberOfAyahs: 11,
      place: 'Meccan'),
  Surah(
      number: 102,
      name: 'التكاثر',
      enName: 'At-Takaathur',
      enNameTrans: 'Competition',
      numberOfAyahs: 8,
      place: 'Meccan'),
  Surah(
      number: 103,
      name: 'العصر',
      enName: 'Al-Asr',
      enNameTrans: 'The Declining Day, Epoch',
      numberOfAyahs: 3,
      place: 'Meccan'),
  Surah(
      number: 104,
      name: 'الهمزة',
      enName: 'Al-Humaza',
      enNameTrans: 'The Traducer',
      numberOfAyahs: 9,
      place: 'Meccan'),
  Surah(
      number: 105,
      name: 'الفيل',
      enName: 'Al-Fil',
      enNameTrans: 'The Elephant',
      numberOfAyahs: 5,
      place: 'Meccan'),
  Surah(
      number: 106,
      name: 'قريش',
      enName: 'Quraish',
      enNameTrans: 'Quraysh',
      numberOfAyahs: 4,
      place: 'Meccan'),
  Surah(
      number: 107,
      name: 'الماعون',
      enName: "Al-Maa'un",
      enNameTrans: 'Almsgiving',
      numberOfAyahs: 7,
      place: 'Meccan'),
  Surah(
      number: 108,
      name: 'الكوثر',
      enName: 'Al-Kawthar',
      enNameTrans: 'Abundance',
      numberOfAyahs: 3,
      place: 'Meccan'),
  Surah(
      number: 109,
      name: 'الكافرون',
      enName: 'Al-Kaafiroon',
      enNameTrans: 'The Disbelievers',
      numberOfAyahs: 6,
      place: 'Meccan'),
  Surah(
      number: 110,
      name: 'النصر',
      enName: 'An-Nasr',
      enNameTrans: 'Divine Support',
      numberOfAyahs: 3,
      place: 'Medinan'),
  Surah(
      number: 111,
      name: 'المسد',
      enName: 'Al-Masad',
      enNameTrans: 'The Palm Fibre',
      numberOfAyahs: 5,
      place: 'Meccan'),
  Surah(
      number: 112,
      name: 'الإخلاص',
      enName: 'Al-Ikhlaas',
      enNameTrans: 'Sincerity',
      numberOfAyahs: 4,
      place: 'Meccan'),
  Surah(
      number: 113,
      name: 'الفلق',
      enName: 'Al-Falaq',
      enNameTrans: 'The Dawn',
      numberOfAyahs: 5,
      place: 'Meccan'),
  Surah(
      number: 114,
      name: 'الناس',
      enName: 'An-Naas',
      enNameTrans: 'Mankind',
      numberOfAyahs: 6,
      place: 'Meccan'),
];
